### ISSUE TITLE
自频道视频不能下载

### ISSUE THREAD

**Issue by BearChu** [malone6/youku#1]
视频类型： flvhd
视频总时长： 00:03:07
视频总大小: 9.58 MB
++++++++++++++++++++ 该视频共1段 ++++++++++++++++++++
第1段时长： 00:03:07
第1段大小： 9.58 MB
第1段视频地址： None
****************************************************************************************************
视频类型： mp4hd
视频总时长： 00:03:07
视频总大小: 19.72 MB
++++++++++++++++++++ 该视频共1段 ++++++++++++++++++++
第1段时长： 00:03:07
第1段大小： 19.72 MB
第1段视频地址： None
****************************************************************************************************
视频类型： mp4hd2
视频总时长： 00:03:07
视频总大小: 37.04 MB
++++++++++++++++++++ 该视频共1段 ++++++++++++++++++++
第1段时长： 00:03:07
第1段大小： 37.04 MB
第1段视频地址： None
****************************************************************************************************
视频类型： mp4hd3
视频总时长： 00:03:07
视频总大小: 70.78 MB
++++++++++++++++++++ 该视频共1段 ++++++++++++++++++++
第1段时长： 00:03:07
第1段大小： 70.78 MB
第1段视频地址： None
****************************************************************************************************
视频类型： flvhd
视频总时长： 00:00:06
视频总大小: 1.16 MB
++++++++++++++++++++ 该视频共1段 ++++++++++++++++++++
第1段时长： 00:00:06
第1段大小： 1.16 MB
第1段视频地址： http://k.youku.com/player/getFlvPath/sid/049260132399512dfefde/st/flv/fileid/03000201005756ACF08896000032C87E2BE91A-97F6-1E3B-A634-DDEEE48EB109?k=f4c097c33bee3a8d261fa1e1&hd=0&myp=0&ts=7&ypremium=1&ctype=12&ev=1&token=0529&oip=618773704&ep=ciadGE%2BNV80C5irWjT8bM3q3IiNaXP4J9h%2BFg9JjALshT%2B256E2nx5W4R%2FlCFvkZcSB1GOyEqaKS%0AY0FlYflE324Q3jurS%2FqR%2BPPn5dknseV1YhFDAMzXvVSeRjL4&ccode=0401&duration=6&expire=18000&psid=16cfa218241201c5fe594ffc303d853e&ups_client_netip=36.225.188.200&ups_ts=1492601323&ups_userid=&utid=onBdERfZriwCAW+++uM3cVByOa&vid=XMjcwNjU4ODExMg%3D%3D&vkey=A307e77846b034f8fa30e22a72fdc47d7
****************************************************************************************************
视频类型： mp4hd3
视频总时长： 00:00:06
视频总大小: 1.80 MB
++++++++++++++++++++ 该视频共1段 ++++++++++++++++++++
第1段时长： 00:00:06
第1段大小： 1.80 MB
第1段视频地址： http://k.youku.com/player/getFlvPath/sid/049260132399512dfefde/st/flv/fileid/03008001005756AC0E8896000032C87E2BE91A-97F6-1E3B-A634-DDEEE48EB109?k=18299e1ad845a240282c4908&hd=3&myp=0&ts=7&ypremium=1&ctype=12&ev=1&token=0529&oip=618773704&ep=ciadGE%2BNV80C5irWjT8bM3q3IiNaXP4J9h%2BNgdJjALshT%2B256E3RspW4R%2FlCFvkZcSB1GOyEqaKS%0AY0FlYflE324Q3jurS%2FqR%2BPPn5dknseV1YhFDAMzXvVSeRjL4&ccode=0401&duration=6&expire=18000&psid=16cfa218241201c5fe594ffc303d853e&ups_client_netip=36.225.188.200&ups_ts=1492601323&ups_userid=&utid=onBdERfZriwCAW+++uM3cVByOa&vid=XMjcwNjU4ODExMg%3D%3D&vkey=A6f3a1188d2a8848ff70dcaba65f844ba
****************************************************************************************************
视频类型： mp4hd
视频总时长： 00:00:06
视频总大小: 1.76 MB
++++++++++++++++++++ 该视频共1段 ++++++++++++++++++++
第1段时长： 00:00:06
第1段大小： 1.76 MB
第1段视频地址： http://k.youku.com/player/getFlvPath/sid/049260132399512dfefde/st/mp4/fileid/03000801005756AC828896000032C87E2BE91A-97F6-1E3B-A634-DDEEE48EB109?k=19978cd79abd7bd7261fa1e1&hd=1&myp=0&ts=7&ypremium=1&ctype=12&ev=1&token=0529&oip=618773704&ep=ciadGE%2BNV80C5irWjT8bM3q3IiNaXP4J9h%2BFidJjALshT%2B256E3ZxZW4R%2FlCFvkZcSB1GOyEqaKS%0AY0FlYflE324Q3jurS%2FqR%2BPPn5dknseV1YhFDAMzXvVSeRjL4&ccode=0401&duration=6&expire=18000&psid=16cfa218241201c5fe594ffc303d853e&ups_client_netip=36.225.188.200&ups_ts=1492601323&ups_userid=&utid=onBdERfZriwCAW+++uM3cVByOa&vid=XMjcwNjU4ODExMg%3D%3D&vkey=Ad6b63c24ab17d33742ae0648a822a67b
****************************************************************************************************
视频类型： mp4hd2
视频总时长： 00:00:06
视频总大小: 1.80 MB
++++++++++++++++++++ 该视频共1段 ++++++++++++++++++++
第1段时长： 00:00:06
第1段大小： 1.80 MB
第1段视频地址： http://k.youku.com/player/getFlvPath/sid/049260132399512dfefde/st/flv/fileid/03000101005756ACD18896000032C87E2BE91A-97F6-1E3B-A634-DDEEE48EB109?k=067fdba4a1963d292412faba&hd=2&myp=0&ts=7&ypremium=1&ctype=12&ev=1&token=0529&oip=618773704&ep=ciadGE%2BNV80C5irWjT8bM3q3IiNaXP4J9h%2BFgNJjALshT%2B256E2lxpW4R%2FlCFvkZcSB1GOyEqaKS%0AY0FlYflE324Q3jurS%2FqR%2BPPn5dknseV1YhFDAMzXvVSeRjL4&ccode=0401&duration=6&expire=18000&psid=16cfa218241201c5fe594ffc303d853e&ups_client_netip=36.225.188.200&ups_ts=1492601323&ups_userid=&utid=onBdERfZriwCAW+++uM3cVByOa&vid=XMjcwNjU4ODExMg%3D%3D&vkey=A9f30919e5b5c17480837b480f88d0728

只能抓到6秒像广告的视频 希望能破解该算法 感谢
http://v.youku.com/v_show/id_XMjcwNjU4ODExMg==.html

**Comment by malone6** [comment]
看了下你发的链接，是一个付费订阅频道。这种付费视频解析的话和vip解析难度一样……目前还没找到方法 @BearChu

**Comment by BearChu** [comment]
好的 谢谢你 辛苦了 @malone6
